name: '.NET Pack & Push'
inputs:
  packageVersion:  # id of input
    description: 'The version of the package'
    required: true

#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Pack
      working-directory: ./RiotGames.Client
      run: dotnet pack --configuration Release --no-build /p:Version=${{ inputs.version }}
    - name: Push Package to NuGet.org
      working-directory: ./RiotGames.Client/bin/Release
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Push Package to GitHub.com
      working-directory: ./RiotGames.Client/bin/Release
      run: dotnet nuget push *.nupkg  -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/mikaeldui/index.json

#    - run: echo Hello ${{ inputs.who-to-greet }}.
#      shell: bash
#    - id: random-number-generator
#      run: echo "::set-output name=random-id::$(echo $RANDOM)"
#      shell: bash
#    - run: ${{ github.action_path }}/goodbye.sh
#      shell: bash
