name: .NET
on:
  push:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/*'
    - '.github/actions/**'
  pull_request:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/*'
    - '.github/actions/**'
jobs:
  build:
    name: 'Build & Pack'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/dotnet-build-and-pack

  nuget-org:
    name: 'NuGet.org'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/nuget.org-deploy.yml@main
    needs: build
    secrets:
      NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}

  github-packages:
    name: 'GitHub Packages'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/github-packages-deploy.yml@main
    needs: build

  github-release:
    name: 'GitHub Release'
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    uses: mikaeldui/actions/.github/workflows/github-release.yml@main
    needs: [nuget-org, github-packages]
    with:
      github_packages_url: ${{ needs.github-packages.outputs.url }}
      nuget_org_url: ${{ needs.nuget-org.outputs.url }}
