name: .NET

on:
  push:
    branches: [ main ]
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet restore
    - name: Run CodeGen    
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet run --no-restore
    - name: Restore dependencies
      working-directory: ./RiotGames.Client
      run: dotnet restore
    - name: Build    
      working-directory: ./RiotGames.Client
      run: dotnet build --no-restore
