name: .NET
on:
  push:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - 'RiotGames.Client.Tests/**'
    - '.github/workflows/dotnet.yml'
    - '.github/actions/**'
    - 'README.md'
  pull_request:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'    
    - 'RiotGames.Client.Tests/**'
    - '.github/workflows/dotnet.yml'
    - '.github/actions/**'
    - 'README.md'
  workflow_dispatch:
jobs:
  build:
    name: 'Build & Pack'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout'
    - uses: ./.github/actions/dotnet-build-and-pack
      name: 'Build & Pack'
      with:
        RIOT_GAMES_API_TOKEN: ${{ secrets.RIOT_GAMES_API_TOKEN }}
        LOL_USERNAME: ${{ secrets.LOL_USERNAME }}
        LOL_PASSWORD: ${{ secrets.LOL_PASSWORD }}

  nuget-org:
    name: 'NuGet.org'
    uses: mikaeldui/actions/.github/workflows/nuget.org-deploy.yml@main
    needs: build
    with:
      snupkg_artifact_name: 'snupkg'
    secrets:
      NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}

  github-packages:
    name: 'GitHub Packages'
    uses: mikaeldui/actions/.github/workflows/github-packages-deploy.yml@main
    needs: build

  github-release:
    name: 'GitHub Release'
    uses: mikaeldui/actions/.github/workflows/github-release.yml@main
    needs: [nuget-org, github-packages]
    with:
      github_packages_url: ${{ needs.github-packages.outputs.url }}
      nuget_org_url: ${{ needs.nuget-org.outputs.url }}
