name: '.NET Pre-release: Feature Branch'
on: [workflow_call]
  
jobs:
  feature-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push
        uses: ./.github/actions/dotnet-push
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
