name: '.NET Pre-release: Pull Request'
on: 
  workflow_call:
    inputs:
      version:
        description: 'The version being released'
        required: true
        type: string 
    secrets:
      NUGET_ORG_API_KEY:
        required: true  
jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: pull-request
      url: https://www.nuget.org/packages/MikaelDui.RiotGames.Client/${{ inputs.version }}-pull-request.${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push
        uses: ./.github/actions/dotnet-push
        with:
          GITHUB_TOKEN: ${{ github.token }}
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1        
        with:
          message: |
            You can install the NuGet Package for this pull request from [NuGet.org](https://www.nuget.org/packages/MikaelDui.RiotGames.Client/${{ inputs.version }}-pull-request.${{ github.event.pull_request.number }}) using either of these commands:

            Using **Package Manager Console** (non-floating version):

                PM> Install-Package MikaelDui.RiotGames.Client --Version ${{ inputs.version }}-pull-request.${{ github.event.pull_request.number }}

            Using the **.NET CLI** (floating version):

                dotnet add package MikaelDui.RiotGames.Client --version *-pull-request.${{ github.event.pull_request.number }}

            Using a PackageReference (floating version):

                <PackageReference Include="MikaelDui.RiotGames.Client" Version="*-pull-request.${{ github.event.pull_request.number }}" />
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
