name: '.NET Pre-release: Feature Branch'
on: 
  workflow_call:
    inputs:
      version:
        description: 'The version being released'
        required: true
        type: string 
    secrets:
        NUGET_ORG_API_KEY:
          required: true
jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: feature-branch
      url: https://www.nuget.org/packages/MikaelDui.RiotGames.Client/${{ inputs.version }}-feature.${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push
        uses: ./.github/actions/dotnet-push
        with:
          GITHUB_TOKEN: ${{ github.token }}
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
