name: .NET Release
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub Token used to push the package to GitHub'
        required: true
        type: string
      NUGET_ORG_API_KEY:
        description: 'NuGet.org token used to push the package to NuGet.org'
        required: true
        type: string
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push
        uses: ./.github/actions/dotnet-push
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
