name: .NET
on:
  push:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/*'
    - '.github/actions/**'
  pull_request:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/*'
    - '.github/actions/**'
jobs:
  build:
    name: 'Build & Pack'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/dotnet-build-and-pack

  nuget-org:
    name: 'NuGet.org'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/nuget.org-deploy.yml@main
    needs: build
    secrets:
      NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}

  github-packages:
    name: 'GitHub Packages'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/github-packages-deploy.yml@main
    needs: build

  github-release:
    name: 'GitHub Release'
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    uses: mikaeldui/actions/.github/workflows/github-release.yml@main
    needs: [nuget-org, github-packages]
    with:
      github_packages_url: ${{ needs.github-packages.outputs.url }}
      nuget_org_url: ${{ needs.nuget-org.outputs.url }}

  github-pull-request-comment:
    name: 'GitHub Pull Request Comment'
    if: ${{ github.event_name == 'pull_request' }}
    needs: [nuget-org, github-packages]
    runs-on: ubuntu-latest
    steps:

      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Package Version
        uses: mikaeldui/actions/nupkg/info@main
        id: package
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1        
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            You can install the NuGet Package for this pull request from [NuGet.org][nuget.org] or [GitHub Packages][github-packages] using either of these commands:

            Using the **Package Manager Console** (non-floating version):

                PM> Install-Package ${{ steps.package.outputs.name }} --Version ${{ steps.package.outputs.version }}

            Using the **.NET CLI** (floating version):

                dotnet add package ${{ steps.package.outputs.name }} --version *-pull-request.${{ github.event.pull_request.number }}

            Using a PackageReference (floating version):

                <PackageReference Include="${{ steps.package.outputs.name }}" Version="*-pull-request.${{ github.event.pull_request.number }}" />

            [github-packages]: ${{ needs.github-packages.outputs.url }}
            [nuget.org]: ${{ needs.nuget-org.outputs.url }}
