name: .NET CI

on:
  push:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet restore
    - name: Run CodeGen    
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet run --no-restore
    - name: Restore dependencies
      working-directory: ./RiotGames.Client
      run: dotnet restore
    - name: Build    
      working-directory: ./RiotGames.Client
      run: dotnet build --no-restore      
    - name: Restore dependencies
      working-directory: ./RiotGames.Client.Tests
      run: dotnet restore
    - name: Build    
      working-directory: ./RiotGames.Client.Tests
      run: dotnet build --no-restore
    - name: Test    
      working-directory: ./RiotGames.Client.Tests
      run: dotnet test --no-build --verbosity normal
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Pack Release
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      working-directory: ./RiotGames.Client
      run: dotnet pack --no-build /p:Version=12.1.1+${{ github.run_id }}.${{ steps.vars.outputs.sha_short }}
    - name: Pack Feature
      if: ${{ startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push' }}
      working-directory: ./RiotGames.Client
      run: dotnet pack --no-build /p:Version=12.1.1-feature.${{ GITHUB_REF##*/ }}+${{ github.run_id }}.${{ steps.vars.outputs.sha_short }}
    - name: Pack Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      working-directory: ./RiotGames.Client
      run: dotnet pack --no-build /p:Version=12.1.1-pull-request.${{ github.event.pull_request.number }}+${{ github.run_id }}.${{ steps.vars.outputs.sha_short }}
