name: .NET

on:
  push:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/**'
  pull_request:
    paths:
    - 'RiotGames.Client/**'    
    - 'RiotGames.Client.CodeGeneration/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 'Code Generation: Restore dependencies'
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet restore
    - name: 'Code Generation: Run'    
      working-directory: ./RiotGames.Client.CodeGeneration
      run: dotnet run --configuration Release --no-restore
    - name: 'Riot Games Client: Restore dependencies'
      working-directory: ./RiotGames.Client
      run: dotnet restore
    - name: 'Riot Games Client: Build'  
      working-directory: ./RiotGames.Client
      run: dotnet build --configuration Release --no-restore /nowarn:CS8669    
    - name: 'Tests: Restore dependencies'
      working-directory: ./RiotGames.Client.Tests
      run: dotnet restore
    - name: 'Tests: Build' 
      working-directory: ./RiotGames.Client.Tests
      run: dotnet build --configuration Release --no-restore
    - name: 'Tests: Run Tests'   
      working-directory: ./RiotGames.Client.Tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Prepare packaging
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"      
      
    - name: Pack Release
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      uses: ./.github/actions/dotnet-pack-and-publish-artifact
      with:
        version: 12.1.1.${{ github.run_number }}+${{ steps.vars.outputs.sha_short }}        
    - name: Pack Feature
      if: ${{ startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push' }}
      uses: ./.github/actions/dotnet-pack-and-publish-artifact
      with:
        version: 12.1.1.${{ github.run_number }}-feature.${GITHUB_REF##*/}+${{ steps.vars.outputs.sha_short }}
    - name: Pack Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/dotnet-pack-and-publish-artifact
      with:
        version: 12.1.1.${{ github.run_number }}-pull-request.${{ github.event.pull_request.number }}+${{ steps.vars.outputs.sha_short }}
        
  release:
    uses: .github/workflows/dotnet-release.yml@features/riot-games-dotnet-client
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: build
