name: GitHub Packages Deployment
on: [ workflow_call ]
jobs:
  push:
    name: 'Push to GitHub Packages'
    runs-on: ubuntu-latest
    environment: 
      name: github-packages
      url: https://github.com/mikaeldui/riot-games-dotnet-client/packages/1184018?version=${{ steps.version.outputs.version }}
    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Download NuGet Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      
      - name: Get Package Version
        uses: mikaeldui/actions/nuget-package-version@main
        id: version
        
      - name: Push
        uses: mikaeldui/actions/dotnet-push@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
