name: NuGet.org Deployment
on: 
  workflow_call:      
    secrets:
      NUGET_ORG_API_KEY:
        required: true
jobs:
  push:
    name: 'Push to NuGet.org'
    runs-on: ubuntu-latest
    environment: 
      name: nuget.org
      url: https://www.nuget.org/packages/MikaelDui.RiotGames.Client/${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Download NuGet Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Get Package Version
        uses: mikaeldui/actions/nuget-package-version@main
        id: version
        
      - name: Push to NuGet.org
        uses: mikaeldui/actions/dotnet-push@main
        with:
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}