name: NuGet.org Push
on: 
  workflow_call:      
    secrets:
      NUGET_ORG_API_KEY:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    environment: 
      name: nuget.org
      url: https://www.nuget.org/packages/MikaelDui.RiotGames.Client/${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Download NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push
        uses: ./.github/actions/dotnet-push
        with:
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
      - name: Package Version
        id: version
        uses: ./.github/actions/nuget-package-version
